global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#all-monitoring'
        send_resolved: true

